mtproto-proxy:
    image: telegrammessenger/proxy
    container_name: mtproto-proxy
    ports:
      - 443:443
    restart: always
    volumes:
      - proxy-config:/data
    environment:
      - WORKERS=1
      - SECRET=a61b1f62701e1bf1a407b98d70768457
